name: calcolator
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <3.0.0'


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2
  font_awesome_flutter: ^10.4.0
  math_expressions: ^2.3.1
  function_tree: ^0.8.13


dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true
  fonts:
    - family: Font
      fonts:
        - asset: assets/fonts/font.ttf
    - family: Digital
      fonts:
        - asset: assets/fonts/digital.ttf
        - asset: assets/fonts/italic.ttf


